#ifndef CHARACTER_H
#define CHARACTER_H

#define CHARACTER_WIDTH 8
#define CHARACTER_HEIGHT 16
#define CHARACTER_NUMBER 96

extern unsigned char character[CHARACTER_NUMBER - 1][CHARACTER_HEIGHT][CHARACTER_WIDTH];

#endif
